### ISSUE TITLE
Wire up jmp's loss scaling support for fp16

### ISSUE THREAD

**Issue by dlwh** [stanford-crfm/levanter#122]
If we're gonna have to run on v100s, we're gonna need to support fp16 (😱). Jmp makes this reasonably easy to do: https://github.com/deepmind/jmp#loss-scaling

Needs to be wired up, put in configs as appropriate, and debugged.

**Comment by alat-rights** [comment]
Looking into this

Codepoints:
- https://github.com/stanford-crfm/levanter/blob/6ab19c26ffc2c92772475e5ac87126aece863d3f/src/levanter/models/loss.py
- https://github.com/stanford-crfm/levanter/blob/6ab19c26ffc2c92772475e5ac87126aece863d3f/src/levanter/config.py
- https://github.com/stanford-crfm/levanter/blob/6ab19c26ffc2c92772475e5ac87126aece863d3f/src/levanter/data/text.py#L109
- https://github.com/stanford-crfm/levanter/blob/6ab19c26ffc2c92772475e5ac87126aece863d3f/src/levanter/compat/hf_checkpoints.py#L718
- https://github.com/stanford-crfm/levanter/blob/6ab19c26ffc2c92772475e5ac87126aece863d3f/src/levanter/models/backpack.py#L196
- https://github.com/stanford-crfm/levanter/blob/6ab19c26ffc2c92772475e5ac87126aece863d3f/tests/test_longformer.py#L20
- https://github.com/stanford-crfm/levanter/blob/6ab19c26ffc2c92772475e5ac87126aece863d3f/docs/Overview.md?plain=1#L12

**Comment by dlwh** [comment]
i don't think i'm going to do this
