### ISSUE TITLE
JSON serialization performance

### ISSUE THREAD

**Issue by yifanmai** [stanford-crfm/levanter#133]
dataclasses_json could be a performance bottleneck. dataclasses_json is reflection-based (like Dacite), which is an order of magnitude slower than codegen-based approaches (like cattrs).

See:
- https://github.com/lidatong/dataclasses-json/issues/228
- https://github.com/Fatal1ty/mashumaro#benchmark

**Comment by dlwh** [comment]
Good to know. I kind of doubt it'll matter here? I only use it for metadata for the caches. The metadata is like 500B per chunk, 3-10K per cache, and roughly a similar amount per shard. Even with Python as slow as it is, I'd hope this isn't a big deal?

**Comment by yifanmai** [comment]
Yeah actually I think we can ignore this because it's not on the performance critical path. I got confused as to where JSON is used.
