### ISSUE TITLE
Inconsistent Weight File Structure after the Initialization Change

### ISSUE THREAD

**Issue by Ivan-Zhou** [stanford-crfm/levanter#169]
With the new change on class initialization (from https://github.com/stanford-crfm/levanter/pull/150/ or after), the structure of weights file changed; as a result, we could not load models trained before May into the current GPT2 model. 

For example: there is now `stacked` term between `transformer/blocks/` and `attn`:
- Path before: `gs://levanter-checkpoints/dev/clean-snowball-990/step-10000/model/transformer/blocks/attn/`
- Path expected now: `gs://levanter-checkpoints/dev/clean-snowball-990/step-10000/model/transformer/blocks/stacked/attn/`

I found this by trying to load this weight to the new Gpt2 implementation and run a consistency test. I received a Value Error that the expected Metadata is not found:

```
src/levanter/checkpoint.py:266: in load_checkpoint
    model = tree_deserialize_leaves_tensorstore(os.path.join(checkpoint_path, "model"), model)
src/levanter/tensorstore_serialization.py:109: in tree_deserialize_leaves_tensorstore
    return asyncio.run(_do_deserialize())
/nlp/scr/ivanzhou/miniconda3/envs/levanter/lib/python3.10/asyncio/runners.py:44: in run
    return loop.run_until_complete(main)
/nlp/scr/ivanzhou/miniconda3/envs/levanter/lib/python3.10/asyncio/base_events.py:649: in run_until_complete
    return future.result()
src/levanter/tensorstore_serialization.py:106: in _do_deserialize
    values = await asyncio.gather(*leaves)
src/levanter/tensorstore_serialization.py:87: in _deserialize_one_leaf
    return await load_array_from_tensorstore(spec)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

spec = {'driver': 'zarr', 'kvstore': {'bucket': 'levanter-checkpoints', 'driver': 'gcs', 'path': 'dev/clean-snowball-990/step-10000/model/transformer/blocks/stacked/ln_1/weight'}}

    async def load_array_from_tensorstore(spec):
>       t: TensorStore = await tensorstore.open(tensorstore.Spec(spec), context=gda_ser.TS_CONTEXT)
E       ValueError: NOT_FOUND: Error opening "zarr" driver: Metadata at gs://levanter-checkpoints/dev/clean-snowball-990/step-10000/model/transformer/blocks/stacked/ln_1/weight/.zarray does not exist [tensorstore_spec='{\"context\":{\"
cache_pool\":{},\"data_copy_concurrency\":{},\"gcs_request_concurrency\":{},\"gcs_request_retries\":{},\"gcs_user_project\":{}},\"driver\":\"zarr\",\"kvstore\":{\"bucket\":\"levanter-checkpoints\",\"driver\":\"gcs\",\"path\":\"dev/clea
n-snowball-990/step-10000/model/transformer/blocks/stacked/ln_1/weight/\"}}'] [source locations='tensorstore/driver/driver.cc:117']

src/levanter/tensorstore_serialization.py:78: ValueError
```

**Comment by dlwh** [comment]
I broke this when I introduced `Stacked`. It's not my favorite but I can probably convert old checkpoints. I had expected that you'd use the same code version for export, but I could see that not being realistic. (I think all you have to do it is `gsutil cp gs://levanter-checkpoints/dev/clean-snowball-990/step-10000/model/transformer/blocks/* gs://levanter-checkpoints/dev/clean-snowball-990/step-10000/model/transformer/blocks/stacked/` (probably i'd make a backup first though!)
