### ISSUE TITLE
Profile FLOP Utilization on TPU

### ISSUE THREAD

**Issue by Ivan-Zhou** [stanford-crfm/levanter#182]
measure FLOP (via the $6ND$ calculation)  utilization for either GPT-2 or the “tutorial transformer” at various scales, and ideally get up to 65B

Tutorial Transformer: https://colab.research.google.com/drive/1QX4yH3zRFF3Xiibf1aahETcSQ5nbcUMz?usp=sharing
Tracking Sheet: https://docs.google.com/spreadsheets/d/1xFiZk0p5OtEuT7kfK7IZRgLgQ6QVXN4DBf7NySvzERw/edit#gid=0

**Comment by Ivan-Zhou** [comment]
I profiled a GPT2-Small training job on V3-32 for 100 steps. I saved the profiled outputs here: `gsutil ls gs://levanter-data/dev/ivan/profiling/gpt2_small_100_steps_0610/`. Note that it contains 4 different folders from 4 hosts (4x v3-8)
```
$ gsutil ls gs://levanter-data/dev/ivan/profiling/gpt2_small_100_steps_0610/
gs://levanter-data/dev/ivan/profiling/gpt2_small_100_steps_0610/2023_06_10_23_53_17/
gs://levanter-data/dev/ivan/profiling/gpt2_small_100_steps_0610/2023_06_10_23_53_18/
gs://levanter-data/dev/ivan/profiling/gpt2_small_100_steps_0610/2023_06_10_23_53_44/
gs://levanter-data/dev/ivan/profiling/gpt2_small_100_steps_0610/2023_06_10_23_53_45/
```

To view the profile files on Tensorboard, here's the setup needed:
1. Install the latest tensorflow, tensorboard, and tensorboard-plugin-profile. Plugin profile is needed to view the profiler results page; otherwise, Tensorboard will complain that `There’s no dashboard by the name of “profile”`. Tensorflow is needed for profile plugin to work. 
```
pip install --upgrade tensorflow tensorboard tensorboard-plugin-profile
```
2. You need to **downgrade** protobuf to `3.20.*`
```
pip install protobuf==3.20.3
```
Otherwise, it cannot load the profile plugin, as shown in the error message below: 
```
File "/nlp/scr/ivanzhou/miniconda3/envs/levanter/lib/python3.10/site-packages/tensorboard_plugin_profile/convert/raw_to_tool_data.py", line 29, in <module>
    from tensorboard_plugin_profile.convert import input_pipeline_proto_to_gviz
  File "/nlp/scr/ivanzhou/miniconda3/envs/levanter/lib/python3.10/site-packages/tensorboard_plugin_profile/convert/input_pipeline_proto_to_gviz.py", line 28, in <module>
    from tensorboard_plugin_profile.protobuf import input_pipeline_pb2
  File "/nlp/scr/ivanzhou/miniconda3/envs/levanter/lib/python3.10/site-packages/tensorboard_plugin_profile/protobuf/input_pipeline_pb2.py", line 17, in <module>
    from tensorboard_plugin_profile.protobuf import diagnostics_pb2 as plugin_dot_tensorboard__plugin__profile_dot_protobuf_dot_diagnostics__pb2
  File "/nlp/scr/ivanzhou/miniconda3/envs/levanter/lib/python3.10/site-packages/tensorboard_plugin_profile/protobuf/diagnostics_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/nlp/scr/ivanzhou/miniconda3/envs/levanter/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```
I don't think it is necessary to set `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python`. It will make the loading very, very slow, given the large file we have.

**Comment by Ivan-Zhou** [comment]
This is how I set up the profiler: https://github.com/stanford-crfm/levanter/blob/3431a2864bebe9937d8f959048ad844c70357a98/examples/gpt2_example.py#L275-L278
1. `start_server` allows to view the profiler results during training. 
1. `start_trace` and `stop_trace` allows to save profiler files at the end of the training.

**Comment by dlwh** [comment]
great! probably good to throw this in too https://jax.readthedocs.io/en/latest/_autosummary/jax.profiler.StepTraceAnnotation.html#jax.profiler.StepTraceAnnotation
