### ISSUE TITLE
Experiment with various gradient checkpointing techniques

### ISSUE THREAD

**Issue by dlwh** [stanford-crfm/levanter#2]
I've got recursive checkpointing working, but we may want to consider the sqrt(n) checkpointing, or something in between?? https://github.com/cybertronai/gradient-checkpointing

The advantage of sqrt(n) checkpointing is that it can implemented with two scans/folds, which makes it much easier on the jit

**Comment by patrick-kidger** [comment]
I saw this thread referenced in the above links, so if it helps anyone here, [Equinox](http://github.com/patrick-kidger/equinox) now supports while loops with recursive checkpointing. See also [this comment](https://github.com/google/jax/issues/2139#issuecomment-1439334364).
