### ISSUE TITLE
Invalid discord link in readme

### ISSUE THREAD

**Issue by rohan-mehta-1024** [stanford-crfm/levanter#282]
The link to the discord in the readme, from this sentence: "You can also find us in the #levanter channel on the unofficial [Jax LLM Discord](https://discord.gg/FkRGNX3ND)" seems to have expired? Just to spell things out this is the actual link: https://discord.gg/FkRGNX3ND

**Comment by dlwh** [comment]
sorry about that: https://discord.gg/CKazXcbbBm
