### ISSUE TITLE
MFU numbers

### ISSUE THREAD

**Issue by vwxyzjn** [stanford-crfm/levanter#290]
Hi all, this is such a cool project! Thanks for doing this.

I was wondering if you have any MFU numbers on models of different sizes, similar to https://github.com/google/maxtext#runtime-performance-results. I am interested in building up an RLHF pipeline using levanter with https://github.com/vwxyzjn/lm-human-preference-details.

**Comment by dlwh** [comment]
Hi @vwxyzjn ,

Thanks! You can see them here: https://github.com/stanford-crfm/levanter/blob/main/docs/Levanter-1.0-Release.md#training-performance-on-tpu

We're definitely not as good as maxtext, but we're not too far off either! I'd love to figure out the gap. 

The smaller model numbers should be significantly better now. I removed a major source of overhead that was affecting them more.

**Comment by dlwh** [comment]
Also that's a very cool project. Please let me know if you need help/support. We're making some changes right now to clean things up and to support llama.
