### ISSUE TITLE
Mistral support

### ISSUE THREAD

**Issue by maximegmd** [stanford-crfm/levanter#361]
Hello,

I am new to the project and am interested in training Mistral 7b, could someone give me some directions on how to add support for this model?

Thank!

**Comment by dlwh** [comment]
Hi @maximegmd ,

It's unfortunately a bit of a porting exercise, but I think it's not too bad here. We have a general guide for adding new models here: https://levanter.readthedocs.io/en/latest/Port-Models/

Mistral is basically the same as Llama with AFAIK two differences: grouped query attention and sliding window attention. 

Implementing sliding window attention efficiently isn't trivial, but we have an implementation here: https://github.com/stanford-crfm/levanter/blob/774464ea8fd7f020998259e3951118207e06731f/src/levanter/models/longformer.py#L11

or we could just use a mask for now and not take advantage of the masking...

GQA shouldn't be too hard, but I haven't thought about it much.

@J38 has expressed interest in taking this on, but lmk if you're interested in trying your hand at it. Happy to consult.

**Comment by dlwh** [comment]
(This is done in #435 )
