### ISSUE TITLE
Curious about how jaxtyping is used?

### ISSUE THREAD

**Issue by rohan-mehta-1024** [stanford-crfm/levanter#374]
I was just curious how jaxtyping type annotations are checked within the project, as I was trying to add them to my nanoGPT implementation. The repo for the jaxtyping library says that it needs to be coupled with beartype, typeguard, or some similar other type-checking library to work, but I wasn't able to find any evidence of these libraries in the code here. So I was wondering how this was handled, and what you've found the best approach to be? Is it usually that you just decorate the functions you want to typecheck during development and then remove these decorators from the final codebase, or something like that?

**Comment by dlwh** [comment]
i don't use jaxtyping for much other than some type aliases. they don't work with Haliax NamedArrays and in some ways kinda compete with them. I'd kind of like to write a typechecking plugin for Haliax but it's far, far down my list.
