### ISSUE TITLE
Cannot import levanter module from git as dependency

### ISSUE THREAD

**Issue by 0xc1c4da** [stanford-crfm/levanter#402]
## Summary

When using Levanter as a library, I can import and use as expected from pypi.org, but I cannot directly import Levanter from github, which is also expected behaviour.

## Why does this matter?
As a ML researcher designing models and not training pre-existing models, I want to use Levanter as a training library throughout the entire workflow, from experimentation to large scale training.

I am dependent on other libraries that have upstream changes (in Jax & Jaxlib, that have deprecated the rng key array), that Levanter & Haliax also depend on and have updated to support the changes.

## Expected Behaviour
I can add the git repository as a dependency and Poetry installs the dependency as a module in my environment, just like the pypi version.

## Actual Behaviour
When specifiying the git repository as a dependency, the module is downloaded but not installed

## Steps to Reproduce
Using pypi.org:
`poetry init --name test --python ">=3.10,<3.11" --dependency levanter@1.1 -n && poetry env use python3.10 && poetry update && poetry run python -m levanter`
> ImportError: cannot import name 'TpuCluster' from 'jax._src.clusters' (/home/j/.cache/pypoetry/virtualenvs/test-eXYhkprN-py3.10/lib/python3.10/site-packages/jax/_src/clusters/__init__.py)

The Levanter module is found and is imported

Using Git repository:
`poetry init --name test --python ">=3.10,<3.11" --dependency "git+https://github.com/stanford-crfm/levanter.git" -n && poetry env use python3.10 && poetry update && poetry run python -m levanter`
> /home/j/.cache/pypoetry/virtualenvs/test-eXYhkprN-py3.10/bin/python: No module named levanter

The Levanter module is not found.

## Workaround
I haven't looked into the exact reason for this, the current workaround is to do the `pip install -e .` equivalent as recommended by Levanter which means pulling down the repository manually and referencing the dependency locally with `develop = true`

pyproject.toml snippet:
```pyproject.toml
[tool.poetry.dependencies]
python = ">=3.10,<3.11"
jax = {git = "https://github.com/google/jax.git", rev = "0d6007cbd6a1b43dc2730b62029501c693b7ed29"}
jaxlib = {extras = ["cuda12_pip"], version = "^0.4.23+cuda12.cudnn89", source = "jax-cuda"}
levanter = {path = "vendor/levanter", develop = true} # TODO can't install from git directly, requires pip install -e .
# levanter = {git = "https://github.com/stanford-crfm/levanter.git", rev = "48b540043594f242d88aeb82b6bbc30d43ba80ae"}
```
This results in the Levanter module being successfully imported and up-to-date, but requires levanter being a git submodule for sharing & collaboration i.e
`git submodule add https://github.com/stanford-crfm/levanter.git vendor/levanter`

**Comment by dlwh** [comment]
I think the issue is that JAX recently deprecated some stuff and possibly main isn't working. I will see

**Comment by dlwh** [comment]
oh actually i see. there's no `levanter` main. try `levanter.main.train_lm`

**Comment by dlwh** [comment]
oh nvm. i tried it. i don't understand why a source install doesn't work. I don't understand how poetry works well enough. We use `hatch` to build, so maybe poetry doesn't work with the weird stuff we do in hatch?

**Comment by dlwh** [comment]
You can try using an older jax (0.4.14 maybe?) with the 1.1 release
