### ISSUE TITLE
Add URL to readthedocs page in Levanter's About section

### ISSUE THREAD

**Issue by Ivan-Zhou** [stanford-crfm/levanter#403]
It would be helpful to highlight the URL to our documentation page (https://levanter.readthedocs.io/en/latest/) in Levanter's About section, for better discoverability. 

Here's the instruction on how to do so: https://stackoverflow.com/questions/67217281/adding-github-pages-url-to-github-repositorys-about-section. It would require the admin access.

**Comment by dlwh** [comment]
good idea. fixed
