### ISSUE TITLE
what is gradient_checkpointing_block_size ?

### ISSUE THREAD

**Issue by tjingrant** [stanford-crfm/levanter#446]
What is this knob doing?
I couldn't find where this is used. It exists in many config files:

https://github.com/stanford-crfm/levanter/blob/5fb676718bde29d790c85c4dc593bd5ac2ac1064/src/levanter/models/gpt2.py#L63

Would be nice to have documentation about this.

**Comment by dlwh** [comment]
It's vestigial and doesn't do anything atm, but also should be brought back... #427 has some beginnings of an investigation about bringing it back. 

ATM we remember the outputs of all num_layers activations (but not that attention matrices or mlp intermediates), which makes rematerializing the needed information for that backward pass take O(num_layers) time, which is good, but you
can actually still get O(num_layers) time while remembering only O(sqrt(num_layers)) activations, which could be a huge memory savings in a big model. The block size refers to the number of layers that should be grouped together for this caching.

I didn't explain it very well... here's a longer explanation https://github.com/cybertronai/gradient-checkpointing

I'm gonna close this in favor of #427
