### ISSUE TITLE
Training OOM introduced by Recent Commits

### ISSUE THREAD

**Issue by Ivan-Zhou** [stanford-crfm/levanter#477]
After rebasing to the Main branch on Feb 18, I found my background job started to show OOM. This persisted even if I reduce the train & eval per device batch size by half. After I went back to my old commit before rebasing, the training job could run successfully.

My last rebasing happened on Feb 7, so it should be due to a commit on Main between Feb 7 and Feb 18. 

This issue can be reproduced with this commit and config on V3-64: https://github.com/stanford-crfm/levanter/blob/5f1ae52ab5dc9cc27da2a83be3e7f25cba8e358e/config/llama2_3b_pretrain.yaml

**Comment by dlwh** [comment]
reproduced. trying to track down

**Comment by dlwh** [comment]
bisected to 8f9a3dece8e8153f919c38b7761bd4f892fb4327
