### ISSUE TITLE
Add Gemma support

### ISSUE THREAD

**Issue by dadelani** [stanford-crfm/levanter#525]
Curious if your framework currently supports the Gemma model on TPU

**Comment by dlwh** [comment]
Not right now. Happy to support someone who wants to implement it!

**Comment by rjpower** [comment]
I added support for Gemma (at least working with a 2B configuration) in #587.

**Comment by dlwh** [comment]
oh right, thanks!

**Comment by dadelani** [comment]
Thank you both. Will give it a try for 7B
