### ISSUE TITLE
Add TPU Metrics to Weights and Biases Logging

### ISSUE THREAD

**Issue by Helw150** [stanford-crfm/levanter#544]
For GPUs, I (and I think most folks) am used to debugging memory usage and performance usage using `nvidia-smi`. TPU's don't have a great equivalent for this. Right now, we log a bunch of other system metrics to Weights and Biases but we don't log TPU metrics! 

It looks like there are hookups for TPU monitoring, so it would be a nice QOL improvement to log these to Weights and Biases when jobs are kicked off in a TPU environment.

https://cloud.google.com/tpu/docs/troubleshooting/tpu-vm-monitoring

**Comment by Helw150** [comment]
Maybe turning on Profiler is supposed to do this? For some reason in my current runs, even with Profiler on, nothing gets logged to the Profiler log directory (the jobs are admittedly dying suddenly).

**Comment by dlwh** [comment]
seems like a good idea. probably not gonna do it imminently, but happy to support someone who wants to do it!

**Comment by Helw150** [comment]
Yeah, this was more a note for myself to do at some point!
