### ISSUE TITLE
LoRA layers via dispatch

### ISSUE THREAD

**Issue by ASEM000** [stanford-crfm/levanter#552]
I saw your @dlwh  [tweet](https://twitter.com/dlwh/status/1778267134369595700) and I was curious how you implemented it.

I noticed that in the following:
https://github.com/stanford-crfm/levanter/blob/662f9f68e22b44543521dd1b9b421d86311b2c77/src/levanter/lora.py#L267C1-L283C26

The layers mapping is hardcoded, I think [serket-like](https://serket.readthedocs.io/API/common.html#serket.tree_eval) style of dispatch will be simpler, and more extendable to the user.

Will be able to do something like this for rule definition

```python

@tree_lora.def_lora(Linear)
def _(layer: Linear, *, rank, etc, ..) -> LoRALinear:
     ...
```

Then you can use tree_map to complete the function

```python
def tree_lora(layer, *, rank, etc):
    types = tuple(set(tree_lora.dispatcher.registry) - {object})
    def is_leaf(node: Any) -> bool:
        return isinstance(node, types)
    def map_func(leaf):
       return tree_lora.dispatcher(leaf, rank=rank, ...)
     return jax.tree_util.tree_map(map_func, tree, is_leaf=is_leaf)

tree_lora.dispatcher = functools.dispatch(lambda x, **_: x)
tree_lora.def_lora = tree_lora.dispatcher.register
```

You can also do 

```python
def is_lora(leaf):
   types = tuple(set(tree_lora.dispatcher.registry) - {object})
   return isinstance(leaf, types)
```

LMK WDYT

**Comment by dlwh** [comment]
I don't think this works because of the fancy handling for Stacked? or am i missing something?

**Comment by ASEM000** [comment]
If I understood your correctly,
It should handle containers fine, by calling the tree_lora inside the rule definition on the container components.

**Comment by dlwh** [comment]
ah yeah right. If/when we add more kinds of layers, I'll take a closer look!

**Comment by ASEM000** [comment]
Sounds good, I will close for now.
