### ISSUE TITLE
Launch script multislice

### ISSUE THREAD

**Issue by blahBlahhhJ** [stanford-crfm/levanter#629]
Things I'm going to add to `launch.py`

1. Migrate some commands API from `tpu-vm` to `queued-resources` to work better with multislice training
2. Delete the instance if command fail (regardless of autodelete) so that it won't eat up all the quota after many retries

**Comment by blahBlahhhJ** [comment]
@dlwh @rjpower  FYI

**Comment by rjpower** [comment]
For (1) SGTM, let me know if I can help. Something simple that just runs `queued-resources create` and then polls until the instance is started seems like a good first step.
For (2) don't we normally want to reuse the instance? That's much faster for me in practice than delete/restart. (Or is this for batch job, in which case, sure, makes sense as an option).

**Comment by blahBlahhhJ** [comment]
In my experience when an instance is preempted (suspended), then you cannot create another one with the same name. The suspended instance is going to stay there and take up the quota.

**Comment by dlwh** [comment]
I think you all are taking about slightly different things. If the node is
still up we want to reuse. Otherwise we have to delete the node and queued
resource and recreate

(Russell this is one of the main reasons i do not like queued resources…)

**Comment by blahBlahhhJ** [comment]
@rjpower is there a way to specify which branch to run?

**Comment by rjpower** [comment]
Not specifically. The script packages whatever is in your current
directory, so you can just checkout the branch you want to run.
