### ISSUE TITLE
preemptible in config wasn't registered as capacity_type

### ISSUE THREAD

**Issue by Ivan-Zhou** [stanford-crfm/levanter#657]
After https://github.com/stanford-crfm/levanter/pull/647, my attempt to create preemptible instance keeps failing. Somehow, launch.py wasn't able to pick up `preemptible: true` value from my .config and registered it as preemptible  in `capacity_type`. As a result, it tries to create reserved TPU instances.

**Comment by dlwh** [comment]
fixed in #665
