### ISSUE TITLE
Running on AWS Sagemaker

### ISSUE THREAD

**Issue by MikeMpapa** [stanford-crfm/levanter#664]
Thank you for your work on this amazing framework. I wonder if you have any knowledge on what would be the best way to set Levander up on Sagemaker. I am trying to fine-tune an Anticipatory-Transformer and apparently it needs some source code modifications. 

Should I follow your instructions on running Levanter in a docker container?  (https://github.com/stanford-crfm/levanter/blob/main/docs/Getting-Started-GPU.md#using-a-docker-container)

Any guidance would be really appreciated!

**Comment by dlwh** [comment]
Hi there,

thanks for trying out Levanter! We're a GCP shop mainly with some on-prem GPUs and a tiny bit of other clouds, but no AWS, so I don't have any experience with SageMaker. If it's just GPU instances, then yeah I'd try the GPU docker image or the non-docker route if you'd prefer.

What GPUs are you using?

**Comment by MikeMpapa** [comment]
thanks much for the swift response! Now I am trying to install it on a A10G but I do have access to A100 if is more appropriate.

**Comment by MikeMpapa** [comment]
Also now that you mention GCP I just got the following error trying to run the interactive container in sagemaker as shown [here](https://levanter.readthedocs.io/en/latest/Getting-Started-GPU/#using-a-docker-container).

`Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist)., 401`

Is there a dependency to have a GCP account to work with the container?

**Comment by dlwh** [comment]
I know the nvidia folks run tests on a100 and v100. There's an issue with Ray tests right now on those machines but I think it's a ray bug. I don't recommend v100 just because bf16 is essential.

I don't see why an A10G wouldn't work. I've tested things on 3090, A100, A6000, and H100, but only done quasi-serious things on A100s.

**Comment by dlwh** [comment]
closing this but feel free to reopen if there's something actionable
