### ISSUE TITLE
Permission 'storage.objects.get' denied on resource

### ISSUE THREAD

**Issue by AdrLfv** [stanford-crfm/levanter#677]
I want to launch the project on my GPU (RTX 3060) but when I enter the command `python src/levanter/main/train_lm.py --config_path config/gpt2_small.yaml` I get the following error. I am launching the program from the levanter folder. I tried with "--config" too but it does not work. I did not modify gpt2_small.yaml. I have the same error when I set up a docker and launch with ```python -m levanter.main.train_lm \  --config_path /opt/levanter/config/gpt2_small.yaml```

> INFO:levanter.distributed:Not initializing jax.distributed because no distributed config was provided, and no cluster was detected.
> INFO:jax._src.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
> INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
> INFO:levanter.trainer:Setting run id to 49h5bd1r
> 2024-07-30T00:35:40 - 0 - levanter.tracker.wandb - wandb.py:200 - INFO :: Setting wandb code_dir to /home/adrlfv/Bureau/levanter
> wandb: Currently logged in as: xx (xx). Use `wandb login --relogin` to force relogin
> wandb: Tracking run with wandb version 0.17.5
> wandb: Run data is saved locally in /home/adrlfv/Bureau/levanter/wandb/run-20240730_003541-49h5bd1r
> wandb: Run `wandb offline` to turn off syncing.
> wandb: Syncing run zesty-sunset-23
> wandb: ⭐️ View project at https://wandb.ai/xx/levanter
> wandb: 🚀 View run at https://wandb.ai/xx/levanter/runs/49h5bd1r
> 2024-07-30T00:35:41 - 0 - levanter.distributed - distributed.py:215 - INFO :: No auto-discovered ray address found. Using ray.init('local').
> 2024-07-30T00:35:41 - 0 - levanter.distributed - distributed.py:267 - INFO :: ray.init(address='local', namespace='levanter', **{})
> /usr/lib/python3.10/subprocess.py:1796: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
>   self.pid = _posixsubprocess.fork_exec(
> /usr/lib/python3.10/subprocess.py:1796: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
>   self.pid = _posixsubprocess.fork_exec(
> 2024-07-30 00:35:43,729 INFO worker.py:1772 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
> 2024-07-30T00:35:44 - 0 - levanter.tracker.wandb - wandb.py:200 - INFO :: Setting wandb code_dir to /home/adrlfv/Bureau/levanter
> 2024-07-30T00:35:44 - 0 - levanter.tracker.wandb - wandb.py:200 - INFO :: Setting wandb code_dir to /home/adrlfv/Bureau/levanter
> train:   0%|                                                                                                                                                                              | 0/400000 [00:00<?, ?it/s]2024-07-30T00:35:45 - 0 - levanter.data.shard_cache - shard_cache.py:1266 - INFO :: Loading cache from gs://levanter-data/tokenized/openwebtext/validation
> /home/adrlfv/Bureau/levanter/levanter_env/lib/python3.10/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. 
>   warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
> 2024-07-30T00:35:45 - 0 - google.auth._default - _default.py:683 - WARNING :: No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable
> 2024-07-30T00:35:45 - 0 - levanter.data.text - text.py:298 - ERROR :: error loading cache
> Traceback (most recent call last):
>   File "/home/adrlfv/Bureau/levanter/levanter_env/lib/python3.10/site-packages/gcsfs/core.py", line 525, in _get_object
>     res = await self._call(
>   File "/home/adrlfv/Bureau/levanter/levanter_env/lib/python3.10/site-packages/gcsfs/core.py", line 445, in _call
>     status, headers, info, contents = await self._request(
>   File "/home/adrlfv/Bureau/levanter/levanter_env/lib/python3.10/site-packages/decorator.py", line 221, in fun
>     return await caller(func, *(extras + args), **kw)
>   File "/home/adrlfv/Bureau/levanter/levanter_env/lib/python3.10/site-packages/gcsfs/retry.py", line 126, in retry_request
>     return await func(*args, **kwargs)
>   File "/home/adrlfv/Bureau/levanter/levanter_env/lib/python3.10/site-packages/gcsfs/core.py", line 438, in _request
>     validate_response(status, contents, path, args)
>   File "/home/adrlfv/Bureau/levanter/levanter_env/lib/python3.10/site-packages/gcsfs/retry.py", line 107, in validate_response
>     raise OSError(f"Forbidden: {path}\n{msg}")
> OSError: Forbidden: b/levanter-data/o/tokenized%2Fopenwebtext%2Fvalidation%2Fcache_ledger.json
> xx does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist).
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/adrlfv/Bureau/levanter/src/levanter/data/text.py", line 293, in load
>     cache = ShardCache.load(cache_dir, batch_size=batch_size)
>   File "/home/adrlfv/Bureau/levanter/src/levanter/data/shard_cache.py", line 1267, in load
>     ledger = _load_cache_ledger(cache_dir)
>   File "/home/adrlfv/Bureau/levanter/src/levanter/data/shard_cache.py", line 513, in _load_cache_ledger
> xx does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource

**Comment by dlwh** [comment]
The default cache dirs are set to a stanford-only gcs bucket. You can make your own gcs bucket and use e.g. `--data.cache_dir gs://your-bucket/cache/`

**Comment by AdrLfv** [comment]
Thanks, I had come to that conclusion too
