### ISSUE TITLE
Is there a way to initialize Mistral from a locally downloaded checkpoint? 

### ISSUE THREAD

**Issue by mhmaqbool** [stanford-crfm/levanter#681]
I have tried using
initialize_from_hf: "/path/to/mistral_checkpoint
use_hf_model_config: true

But it tries to go to HF website to get the model checkpoint?

Is it a bug?

**Comment by dlwh** [comment]
yep. seems like a bug. i'm on vacation for another week so I don't know if I'll be able to get to this before then. Are you able to make a private HF repo?

**Comment by hmaqboolnv** [comment]
Is there any update on this bug?
