### ISSUE TITLE
ModuleNotFoundError: No module named 'async_lru'

### ISSUE THREAD

**Issue by mhmaqbool** [stanford-crfm/levanter#720]
Hello,
While running Mistral-7b 

`python -m levanter.main.train_lm --config_path config/mistral_7b.yaml
`
`ModuleNotFoundError: No module named 'async_lru' `

**Comment by dlwh** [comment]
i just added that as a dependency. can you make sure youre dependencies are
up to date (run pip install -e . again)

**Comment by mhmaqbool** [comment]
Yes, you are right. This resolves the issue.

Thanks.

**Comment by dlwh** [comment]
NB that I just merged a change that breaks all caches, so please remove any caches you were using
