### ISSUE TITLE
Levanter unit test issue

### ISSUE THREAD

**Issue by DwarKapex** [stanford-crfm/levanter#733]
Hi @dlwh ,

  Today's JAX-Toolbox nightly for Levanter unit test failed. The job link is [here](https://github.com/NVIDIA/JAX-Toolbox/actions/runs/10938306709/job/30367525704).

 1. One issue is related to a module `zarr3` driver ([link](https://github.com/NVIDIA/JAX-Toolbox/actions/runs/10938306709/job/30367525704#step:7:431))
 2. The other issues are related to `test_attension.py` ([link](https://github.com/NVIDIA/JAX-Toolbox/actions/runs/10938306709/job/30367525704#step:7:573))

Could you please take a look?
Thank you in advance.

**Comment by dlwh** [comment]
ok thanks i think i noticed (1) recently

**Comment by dlwh** [comment]
for (1) could you maybe add `PYTHONPATH=src:.:tests:$PYTHONPATH` (assuming you're in the levanter root)

**Comment by DwarKapex** [comment]
For (1) -- the updating the PYTHONPATH helped.

What about the second one?

**Comment by dlwh** [comment]
Pretty sure (2) is now fixed by #795
